# Generated by Django 2.1.3 on 2020-02-13 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('detail_id', models.AutoField(max_length=32, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=32)),
                ('product_id', models.CharField(max_length=32)),
                ('product_name', models.CharField(max_length=64)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product_quantity', models.IntegerField()),
                ('product_icon', models.CharField(blank=True, max_length=512, null=True)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderMaster',
            fields=[
                ('order_id', models.AutoField(max_length=32, primary_key=True, serialize=False)),
                ('buyer_name', models.CharField(max_length=32)),
                ('buyer_phone', models.CharField(max_length=32)),
                ('buyer_address', models.CharField(max_length=128)),
                ('buyer_openid', models.CharField(max_length=64)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order_status', models.IntegerField(choices=[(4, '已完成'), (3, '待评价'), (2, '已取消'), (1, '已支付')], default=1)),
                ('pay_status', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('pic_id', models.AutoField(primary_key=True, serialize=False)),
                ('pic_url', models.CharField(max_length=255)),
                ('pic_message', models.CharField(max_length=64)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名')),
                ('desc', models.TextField(default='', help_text='类别描述', verbose_name='类别描述')),
                ('category_type', models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目')], help_text='类目级别', verbose_name='类目级别')),
                ('product_icon', models.CharField(blank=True, max_length=512, null=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('product_stock', models.IntegerField(null=True)),
                ('product_status', models.IntegerField(blank=True, default=0, null=True)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('parent_category', models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='account.ProCategory', verbose_name='父类目级别')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=64)),
                ('category_type', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=64)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product_stock', models.IntegerField()),
                ('product_description', models.CharField(blank=True, max_length=64, null=True)),
                ('product_icon', models.CharField(blank=True, max_length=512, null=True)),
                ('product_status', models.IntegerField(blank=True, default=0, null=True)),
                ('category_type', models.CharField(max_length=8)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SellerInfo',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=64)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='orderMaster',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='master_detail', to='account.OrderMaster'),
        ),
    ]
