# Generated by Django 2.1.3 on 2020-02-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200217_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('openid', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='order_status',
            field=models.IntegerField(choices=[(4, '已完成'), (3, '待评价'), (2, '已取消'), (1, '已支付')], default=1),
        ),
    ]
