# Generated by Django 2.1.3 on 2020-02-20 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200217_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='product_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='account.ProductCategory'),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='order_status',
            field=models.IntegerField(choices=[(3, '待评价'), (4, '已完成'), (1, '已支付'), (2, '已取消')], default=1),
        ),
    ]
