# Generated by Django 2.1.3 on 2020-03-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200220_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('openid', models.CharField(max_length=64)),
                ('zhuohao', models.CharField(blank=True, max_length=64, null=True)),
                ('renshu', models.CharField(blank=True, max_length=64, null=True)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='order_status',
            field=models.IntegerField(choices=[(2, '已取消'), (4, '已完成'), (3, '待评价'), (1, '已支付')], default=1),
        ),
    ]
